[package]
name = "quillc_api"
version = "0.1.0"
authors = ["thirdsgames <thirdsgames2018@gmail.com>"]
edition = "2021"
description = "API for invoking quillc"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
quill_target = { path = "../quill_target" }
