var N = null;var sourcesIndex = {};
sourcesIndex["quill"] = {"name":"","files":["cli.rs","main.rs","update.rs"]};
sourcesIndex["quill_analyse"] = {"name":"","files":["lib.rs","values.rs"]};
sourcesIndex["quill_borrow_check"] = {"name":"","files":["lib.rs","ownership.rs"]};
sourcesIndex["quill_common"] = {"name":"","files":["diagnostic.rs","lib.rs","location.rs","name.rs"]};
sourcesIndex["quill_error"] = {"name":"","files":["lib.rs"]};
sourcesIndex["quill_func_objects"] = {"name":"","files":["lib.rs"]};
sourcesIndex["quill_index"] = {"name":"","files":["lib.rs","main_index.rs","type_index.rs","type_resolve.rs"]};
sourcesIndex["quill_install"] = {"name":"","files":["main.rs"]};
sourcesIndex["quill_lexer"] = {"name":"","files":["lib.rs"]};
sourcesIndex["quill_link"] = {"name":"","files":["lib.rs"]};
sourcesIndex["quill_llvm"] = {"name":"","dirs":[{"name":"func","files":["body.rs","lifetime.rs","mod.rs","rvalue.rs"]},{"name":"intrinsics","files":["mod.rs"]},{"name":"repr","files":["any_type.rs","data.rs","llvm_struct.rs","mod.rs"]}],"files":["codegen.rs","debug.rs","lib.rs","monomorphisation.rs"]};
sourcesIndex["quill_lsp"] = {"name":"","files":["backend.rs","diagnostic.rs","main.rs","path.rs","semantic_tokens.rs"]};
sourcesIndex["quill_mir"] = {"name":"","files":["definition.rs","expr.rs","impls.rs","lib.rs","mir.rs","pattern_match.rs","validate.rs"]};
sourcesIndex["quill_monomorphise"] = {"name":"","files":["lib.rs","mono_mir.rs","monomorphisation.rs","monomorphise.rs"]};
sourcesIndex["quill_parser"] = {"name":"","files":["data_types.rs","definition.rs","expr_pat.rs","file.rs","identifier.rs","lib.rs","types.rs","validate.rs","visibility.rs"]};
sourcesIndex["quill_reprs"] = {"name":"","files":["data.rs","lib.rs","sort_types.rs"]};
sourcesIndex["quill_source_file"] = {"name":"","files":["lib.rs"]};
sourcesIndex["quill_target"] = {"name":"","files":["lib.rs"]};
sourcesIndex["quill_type"] = {"name":"","files":["lib.rs"]};
sourcesIndex["quill_type_deduce"] = {"name":"","dirs":[{"name":"hindley_milner","files":["assumptions.rs","constraints.rs","explicit.rs","generate_constraints.rs","mod.rs","solver.rs","substitute.rs"]},{"name":"hir","files":["definition.rs","expr.rs","mod.rs","pattern.rs"]}],"files":["index_resolve.rs","lib.rs","type_check.rs","type_resolve.rs"]};
sourcesIndex["quillc"] = {"name":"","files":["lib.rs"]};
sourcesIndex["quillc_api"] = {"name":"","files":["lib.rs"]};
createSourceSidebar();
