[package]
name = "quill_install"
version = "0.1.0"
authors = ["thirdsgames <thirdsgames2018@gmail.com>"]
edition = "2021"

[dependencies]
console = "0.15.0"
indicatif = "0.16.2"
curl = "0.4.41"
tar = "0.4.37"
flate2 = "1.0.22"
tempdir = "0.3.7"
dirs = "4.0.0"
