[package]
name = "quillc_test_macros"
version = "0.1.0"
authors = ["thirdsgames <thirdsgames2018@gmail.com>"]
edition = "2018"
description = "Procedural macros for generating tests"

[lib]
proc-macro = true

[dependencies]
quote = "^1.0"
