[package]
name = "quill_type"
version = "0.1.0"
authors = ["thirdsgames <thirdsgames2018@gmail.com>"]
edition = "2021"
description = "Provides type information for programs and index entries"

[dependencies]
quill_common = { path = "../quill_common" }
