[package]
name = "quill"
version = "0.1.0"
authors = ["thirdsgames <thirdsgames2018@gmail.com>"]
edition = "2018"

[dependencies]
quill_common = { path = "../quill_common" }
quill_source_file = { path = "../quill_source_file" }
quill_target = { path = "../quill_target" }
quillc_api = { path = "../quillc_api" }

clap = { version = "~2.33.3", features = ["yaml"] }
console = "^0.14"
tracing = "^0.1.25"
tracing-subscriber = "^0.2.16"
serde_json = "1.0"
serde = "1.0"
toml = "0.5"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"]}
