[package]
name = "quill"
version = "0.1.0"
authors = ["thirdsgames <thirdsgames2018@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "~2.33.3", features = ["yaml"] }
quill_target = { path = "../quill_target" }
console = "^0.14"
tracing = "^0.1.25"
tracing-subscriber = "^0.2.16"
