[package]
name = "quill_common"
version = "0.1.0"
authors = ["thirdsgames <thirdsgames2018@gmail.com>"]
edition = "2021"
description = "A small library containing common utilities useful for most components of the project"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
