name: Check and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LLVM_SYS_110_PREFIX: /home/runner/llvm/clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-20.10

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install LLVM
        run: |
          mkdir ~/llvm
          curl -LJO https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-20.10.tar.xz
          tar -xvf clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-20.10.tar.xz -C ~/llvm
          rm clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-20.10.tar.xz

      - name: Install latest nightly rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: Check warnings
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -Dwarnings

      - name: Run test suite
        uses: actions-rs/cargo@v1
        with:
          command: test
