name: test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install LLVM
        uses: thirdsgames/install-llvm-action@v1
        with:
          llvm-version: 11
          env-var: LLVM_SYS_110_PREFIX

      - name: Install latest nightly rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy

      # Cache is disabled since we're using the nightly compiler. It will probably just slow everything down.
      # - name: Cache compiler artifacts
      #   uses: Swatinem/rust-cache@v1

      - name: Download compiler dependencies
        run: cargo run --bin download_compiler_deps

      - name: Run test suite
        uses: actions-rs/tarpaulin@v1
        with:
          args: '-v --out Xml'
      
      - name: Publish coverage
        uses: codecov/codecov-action@v1
        with:
          files: ./cobertura.xml
          fail_ci_if_error: true
          verbose: true
      
      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml
