name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install LLVM
        uses: thirdsgames/install-llvm-action@v1
        with:
          llvm-version: 11
          env-var: LLVM_SYS_110_PREFIX

      - name: Install latest stable rust
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy

      - name: Install latest nightly zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: Cache compiler artifacts
        uses: Swatinem/rust-cache@v1

      - name: Build project
        uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --verbose

      - name: Check warnings
        uses: actions-rs/cargo@v1.0.3
        with:
          command: clippy
          args: -- -Dwarnings

      - name: Run test suite
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test
          args: --verbose -- --test-threads=1
