name: Run tests and produce release

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install LLVM
        uses: thirdsgames/install-llvm-action@v1
        with:
          llvm-version: 11
          env-var: LLVM_SYS_110_PREFIX

      - name: Install latest nightly rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy

      - name: Cache compiler artifacts
        uses: Swatinem/rust-cache@v1

      - name: Download compiler dependencies
        run: cargo run --bin download_compiler_deps

      - name: Build project
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Check warnings
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --release -- -Dwarnings

      - name: Run test suite
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --no-fail-fast

      # We also build the rustdoc in this action so that we avoid recompilation.

      - name: Build rustdoc
        if: matrix.os == 'ubuntu-latest'
        run: cargo doc --workspace --no-deps

      - name: Create index.html
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "<!DOCTYPE html>" >> target/doc/index.html
          echo "<html>" >> target/doc/index.html
          echo "<head>" >> target/doc/index.html
          echo "<meta http-equiv="refresh" content=\"0; URL=quill/index.html\" />" >> target/doc/index.html
          echo "</head>" >> target/doc/index.html
          echo "<body>" >> target/doc/index.html
          echo "<p>Redirecting to <a href=\"quill/index.html\">quill/index.html</a>...</p>" >> target/doc/index.html
          echo "</body>" >> target/doc/index.html
          echo "</html>" >> target/doc/index.html

      - name: Deploy rustdoc
        if: matrix.os == 'ubuntu-latest'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          force_orphan: true

      # Now create a release and upload the compiler.

      - name: Upload compiler
        uses: actions/upload-artifact@v2
        with:
          name: quill-${{ matrix.os }}
          path: |
            target/quill*
            !**.d

  create-release:
    runs-on: ubuntu-latest
    needs: compile-llvm
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2

      - name: Create GitHub release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: latest
          files: |
            quill-*/*
