name: update latest branch

on:
  schedule:
    # Run once per day at 4am UTC.
    - cron: "0 4 * * *"

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      # Run at most once per day.
      # https://github.community/t/how-to-trigger-workflow-run-once-a-week-if-push-has-occurred/18124/2
      - name: Create cache file
        run: |
          mkdir check-SHA
          echo ${{ github.sha }} > github-sha.txt
      - name: Check SHA
        id: check_sha
        uses: actions/cache@v1
        with:
          path: check-SHA
          key: check-SHA-${{ github.sha }}

      - name: Checkout
        if: steps.check_sha.outputs.cache-hit != 'true'
        uses: actions/checkout@v2.3.4

      - name: Create Pull Request
        id: cpr
        if: steps.check_sha.outputs.cache-hit != 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          branch: latest
          delete-branch: false
          labels: automated

      - uses: peter-evans/enable-pull-request-automerge@v1
        if: steps.check_sha.outputs.cache-hit != 'true'
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
